version: '2'


networks:
  my-net:


services:
  couchdb1:
    image: hyperledger/fabric-couchdb:x86_64-1.0.6
    container_name: couchdb0
    environments:
      - GODEBUG=netdns=go 
      - COUCHDB_USER= 
      - COUCHDB_PASSWORD= 
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
    ports:
      - 5984:5984
