# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'


# networks:
#   byfn:

volumes:
  orderer.example.com:
  # peer0.org1.example.com:
  # peer1.org1.example.com:
  # peer0.org2.example.com:
  # peer1.org2.example.com:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    # networks:
      # - byfn

