version: "3"
networks:
  hyperledger-ov:
    external:
      name: hyperledger-ov
services:
  peer0_org1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: peer0.org1.qsoft.com
    image: hyperledger/fabric-peer:x86_64-1.0.2
    networks:
      hyperledger-ov:
        aliases:
        - peer0.org1.qsoft.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org1.qsoft.com
    - CORE_PEER_ADDRESS=peer0.org1.qsoft.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.qsoft.com:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-ov
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.qsoft.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/org1.qsoft.com/peers/peer0.org1.qsoft.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/org1.qsoft.com/peers/peer0.org1.qsoft.com/tls:/etc/hyperledger/fabric/tls
    - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
  peer0_org2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: peer0.org2.qsoft.com
    image: hyperledger/fabric-peer:x86_64-1.0.2
    networks:
      hyperledger-ov:
        aliases:
        - peer0.org2.qsoft.com
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org2.qsoft.com
    - CORE_PEER_ADDRESS=peer0.org2.qsoft.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.qsoft.com:7051
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger-ov
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.qsoft.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/org2.qsoft.com/peers/peer0.org2.qsoft.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/org2.qsoft.com/peers/peer0.org2.qsoft.com/tls:/etc/hyperledger/fabric/tls
